export enum BekreftOpplysningerKeys {
  LABEL = 'BEKREFTOPPLYSNINGER_BEKREFT_LABEL',
  OPPLYSNINGER = 'BEKREFTOPPLYSNINGER_BEKREFT_OPPLYSNINGER',
  OPPLYSNINGER_OVERSKRIFT = 'BEKREFTOPPLYSNINGER_BEKREFT_OPPLYSNINGER_OVERSKRIFT'
}
