export enum KroniskKravPeriodeKeys {
  KRONISK_KRAV_PERIODE_FRA = 'KRONISK_KRAV_PERIODE_FRA',
  KRONISK_KRAV_PERIODE_TIL = 'KRONISK_KRAV_PERIODE_TIL',
  KRONISK_KRAV_PERIODE_FORMAT = 'KRONISK_KRAV_PERIODE_FORMAT'
}
