export enum KroniskKravKeys {
  KRONISK_KRAV_INFO = 'KRONISK_KRAV_INFO',
  KRONISK_KRAV_EMPLOYEE = 'KRONISK_KRAV_EMPLOYEE',
  KRONISK_KRAV_PERIOD_AWAY = 'KRONISK_KRAV_PERIOD_AWAY',
  KRONISK_KRAV_PERIOD_INFO = 'KRONISK_KRAV_PERIOD_INFO',
  KRONISK_KRAV_ADD_PERIOD = 'KRONISK_KRAV_ADD_PERIOD',
  KRONISK_KRAV_SUBMIT = 'KRONISK_KRAV_SUBMIT',
  KRONISK_KRAV_SIDETITTEL = 'KRONISK_KRAV_SIDETITTEL',
  KRONISK_KRAV_TITLE = 'KRONISK_KRAV_TITLE',
  KRONISK_KRAV_SUBTITLE = 'KRONISK_KRAV_SUBTITLE',
  KRONISK_KRAV_ARBEIDSTID_TAPT = 'KRONISK_KRAV_ARBEIDSTID_TAPT',
  KRONISK_KRAV_PERIODE_FRA = 'KRONISK_KRAV_PERIODE_FRA',
  KRONISK_KRAV_PERIODE_TIL = 'KRONISK_KRAV_PERIODE_TIL',
  KRONISK_KRAV_ENDRE = 'KRONISK_KRAV_ENDRE'
}
