export enum LoggetUtAdvarselKeys {
  LOGGET_UT_ADVARSEL_LOGGET_UT = 'LOGGET_UT_ADVARSEL_LOGGET_UT',
  LOGGET_UT_ADVARSEL_INFO = 'LOGGET_UT_ADVARSEL_INFO',
  LOGGET_UT_ADVARSEL_LOGIN = 'LOGGET_UT_ADVARSEL_LOGIN'
}
