export enum TokenFornyetKeys {
  TOKEN_FORNYET_TITLE = 'TOKEN_FORNYET_TITLE',
  TOKEN_FORNYET_INFO = 'TOKEN_FORNYET_INFO',
  TOKEN_FORNYET_SIDETITTEL = 'TOKEN_FORNYET_SIDETITTEL',
  TOKEN_FORNYET_LOGIN = 'TOKEN_FORNYET_LOGIN'
}
