export enum ServerFeilAdvarselKeys {
  SERVER_FEIL_ADVARSEL_HEADING = 'SERVER_FEIL_ADVARSEL_HEADING',
  SERVER_FEIL_ADVARSEL_TEXT = 'SERVER_FEIL_ADVARSEL_TEXT',
  SERVER_FEIL_ADVARSEL_HIDE = 'SERVER_FEIL_ADVARSEL_HIDE'
}
