export enum Omplassering {
  JA = 'JA',
  NEI = 'NEI',
  IKKE_MULIG = 'IKKE_MULIG'
}

export enum OmplasseringAarsak {
  MOTSETTER = 'MOTSETTER',
  FAAR_IKKE_KONTAKT = 'FAAR_IKKE_KONTAKT',
  IKKE_ANDRE_OPPGAVER = 'IKKE_ANDRE_OPPGAVER',
  HELSETILSTANDEN = 'HELSETILSTANDEN'
}

export enum Tiltak {
  TILPASSET_ARBEIDSTID = 'TILPASSET_ARBEIDSTID',
  HJEMMEKONTOR = 'HJEMMEKONTOR',
  TILPASSEDE_ARBEIDSOPPGAVER = 'TILPASSEDE_ARBEIDSOPPGAVER',
  ANNET = 'ANNET'
}
