export enum GravidKvitteringKeys {
  GRAVID_KVITTERING_TITTEL = 'GRAVID_KVITTERING_TITTEL',
  GRAVID_KVITTERING_INGRESS = 'GRAVID_KVITTERING_INGRESS',
  GRAVID_KVITTERING_ADVARSEL = 'GRAVID_KVITTERING_ADVARSEL',
  GRAVID_KVITTERING_KRAV = 'GRAVID_KVITTERING_KRAV',
  GRAVID_KVITTERING_SENDER_INN = 'GRAVID_KVITTERING_SENDER_INN',
  GRAVID_KVITTERING_VENNLIGST_VENT = 'GRAVID_KVITTERING_VENNLIGST_VENT'
}
