apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fritak-agp-frontend
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  image: {{image}}
  port: 443
  liveness:
    path: /health/is-alive
    initialDelay: 15
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  readiness:
    path: /health/is-ready
    initialDelay: 15
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  ingresses:
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 800m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 256Mi
  env:
    - name: API_GATEWAY
      value: https://api-gw-q1.oera.no/fritakagp
