export enum FravaerTabellKeys {
  FRAVAERTABELL_MONTH = 'FRAVAERTABELL_MONTH',
  FRAVAERTABELL_DAYS = 'FRAVAERTABELL_DAYS',
  FRAVAERTABELL_MONTH_1 = 'FRAVAERTABELL_MONTH_1',
  FRAVAERTABELL_MONTH_2 = 'FRAVAERTABELL_MONTH_2',
  FRAVAERTABELL_MONTH_3 = 'FRAVAERTABELL_MONTH_3',
  FRAVAERTABELL_MONTH_4 = 'FRAVAERTABELL_MONTH_4',
  FRAVAERTABELL_MONTH_5 = 'FRAVAERTABELL_MONTH_5',
  FRAVAERTABELL_MONTH_6 = 'FRAVAERTABELL_MONTH_6',
  FRAVAERTABELL_MONTH_7 = 'FRAVAERTABELL_MONTH_7',
  FRAVAERTABELL_MONTH_8 = 'FRAVAERTABELL_MONTH_8',
  FRAVAERTABELL_MONTH_9 = 'FRAVAERTABELL_MONTH_9',
  FRAVAERTABELL_MONTH_10 = 'FRAVAERTABELL_MONTH_10',
  FRAVAERTABELL_MONTH_11 = 'FRAVAERTABELL_MONTH_11',
  FRAVAERTABELL_MONTH_12 = 'FRAVAERTABELL_MONTH_12'
}
