export enum KroniskSideKeys {
  KRONISK_SIDE_INGRESS = 'KRONISK_SIDE_INGRESS',
  KRONISK_SIDE_ARBEIDSMILJO = 'KRONISK_SIDE_ARBEIDSMILJO',
  KRONISK_SIDE_ARBEIDSMILJO_INGRESS = 'KRONISK_SIDE_ARBEIDSMILJO_INGRESS'
}
