export enum KroniskSideKeys {
  KRONISK_SIDE_SIDETITTEL = 'KRONISK_SIDE_SIDETITTEL',
  KRONISK_SIDE_TITLE = 'KRONISK_SIDE_TITLE',
  KRONISK_SIDE_SUBTITLE = 'KRONISK_SIDE_SUBTITLE',
  KRONISK_SIDE_INGRESS = 'KRONISK_SIDE_INGRESS',
  KRONISK_SIDE_ARBEIDSMILJO = 'KRONISK_SIDE_ARBEIDSMILJO',
  KRONISK_SIDE_ARBEIDSMILJO_INGRESS = 'KRONISK_SIDE_ARBEIDSMILJO_INGRESS',
  KRONISK_SIDE_ARBEIDS_TYPE = 'KRONISK_SIDE_ARBEIDS_TYPE',
  KRONISK_SIDE_PAAKJENNINGER = 'KRONISK_SIDE_PAAKJENNINGER',
  KRONISK_SIDE_ANNET = 'KRONISK_SIDE_ANNET',
  KRONISK_SIDE_IF_DOCUMENTATION = 'KRONISK_SIDE_IF_DOCUMENTATION',
  KRONISK_SIDE_DOCUMENTATION_TEXT = 'KRONISK_SIDE_DOCUMENTATION_TEXT',
  KRONISK_SIDE_UPLOAD = 'KRONISK_SIDE_UPLOAD',
  KRONISK_SIDE_FRAVAER = 'KRONISK_SIDE_FRAVAER',
  KRONISK_SIDE_FRAVAER_DESCRIPTION = 'KRONISK_SIDE_FRAVAER_DESCRIPTION'
}
