export enum KravEndringKvitteringKeys {
  KRAV_ENDRING_KVITTERING_TITTEL = 'KRAV_ENDRING_KVITTERING_TITTEL',
  KRAV_ENDRING_KVITTERING_INGRESS = 'KRAV_ENDRING_KVITTERING_INGRESS',
  KRAV_ENDRING_KVITTERING_OPPRETT_NYTT_KRAV = 'KRAV_ENDRING_KVITTERING_OPPRETT_NYTT_KRAV'
}

export default KravEndringKvitteringKeys;
