export enum KravKvitteringKeys {
  KRAV_KVITTERING_TITTEL = 'KRAV_KVITTERING_TITTEL',
  KRAV_KVITTERING_INGRESS = 'KRAV_KVITTERING_INGRESS',
  KRAV_KVITTERING_OPPRETT_NYTT_KRAV = 'KRAV_KVITTERING_OPPRETT_NYTT_KRAV'
}
