export enum DuplicateSubmissionAdvarselKeys {
  DUPLICATE_SUBMISSION_ADVARSEL_HEADING = 'DUPLICATE_SUBMISSION_ADVARSEL_HEADING',
  DUPLICATE_SUBMISSION_ADVARSEL_TEXT = 'DUPLICATE_SUBMISSION_ADVARSEL_TEXT',
  DUPLICATE_SUBMISSION_ADVARSEL_HIDE = 'DUPLICATE_SUBMISSION_ADVARSEL_HIDE'
}
