export enum KravKvitteringSlettetKeys {
  KRAV_KVITTERING_SLETTET_TITTEL = 'KRAV_KVITTERING_SLETTET_TITTEL',
  KRAV_KVITTERING_SLETTET_INGRESS = 'KRAV_KVITTERING_SLETTET_INGRESS',
  KRAV_KVITTERING_SLETTET_OPPRETT_NYTT_KRAV = 'KRAV_KVITTERING_SLETTET_OPPRETT_NYTT_KRAV'
}

export default KravKvitteringSlettetKeys;
