name: Is alive tests
on: 
  schedule:
    - cron: '15,45 8-16 * * 1,2,3,4,5'  # Kvart på og kvart over i arbeidstiden

env:
  APP: fritak-agp-frontend
  IMAGE: ghcr.io/${{ github.repository }}/fritak-agp-frontend:${{ github.sha }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: "https://npm.pkg.github.com"
      - name: Check out the repository
        uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
            skip-install: true
            args: chrome:headless testalive/ --app-init-delay 60000 --cache --skip-js-errors
