name: Is alive tests
on: 
  schedule:
    - cron: '15,45 8-16 * * 1,2,3,4,5'  # Kvart på og kvart over i arbeidstiden

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: "https://npm.pkg.github.com"
      - name: Check out the repository
        uses: actions/checkout@v1
      - run: yarn install --frozen-lockfile
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
            skip-install: true
            args: chrome:headless testalive/ --app-init-delay 60000 --cache --skip-js-errors
