name: Sjekk etter ubrukte filer og avhengigheter

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  Knip:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      checks: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: "24.0"
          registry-url: "https://npm.pkg.github.com"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - uses: codex-/knip-reporter@7ee82434e4adcb560038aaa59bc647fe8c3c6ee4
