name: Sjekk etter ubrukte filer og avhengigheter

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  Knip:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      checks: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '24.0'
          registry-url: 'https://npm.pkg.github.com'
      - name: Enable Corepack (Yarn 4)
        run: corepack enable
      - name: Cache Yarn (Berry) artifacts
        id: cache-yarn
        uses: actions/cache@v4
        with:
          path: |
            **/.yarn/cache
            **/.yarn/unplugged
            **/.yarn/build-state.yml
            **/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install dependencies
        run: yarn install --immutable
      - uses: codex-/knip-reporter@v2
