name: Sjekk etter ubrukte filer og avhengigheter

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  Knip:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      checks: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version: "24.0"
          registry-url: "https://npm.pkg.github.com"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - uses: codex-/knip-reporter@398e656c485dd1649f06631a4cd2e602c6ccc4f1
