name: Sjekk etter ubrukte filer og avhengigheter

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  Knip:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      checks: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version: "24.0"
          registry-url: "https://npm.pkg.github.com"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - uses: codex-/knip-reporter@438819707021437618b2527e668b0d1e491db05e
