name: Bygg og deploy main

on:
  push:
    branches:
      - main

env:
  APP: fritak-agp-frontend
  DOCKER_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/fritak-agp-frontend
  LATEST_TAG: docker.pkg.github.com/${{ github.repository }}/fritak-agp-frontend:latest
  IMAGE: docker.pkg.github.com/${{ github.repository }}/fritak-agp-frontend:${{ github.sha }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  Bygg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm run-script build
      - uses: actions/upload-artifact@v2
        with:
          name: fritak-frontend-artifact
          path: ${{ github.workspace }}/build/**/*

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: CI=false npm install --no-build
      - run: npm test

  SonarCube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install sonarqube-scanner
      - run: node run-sonar.js


  Versjon:
    needs: Bygg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          git config --global user.email "helsearbeidsgiver@nav.no"
          git config --global user.name "HelseArbeidsgiver"
          npm version patch
          git push
