name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write

jobs:
  e2e:
    uses: navikt/helsearbeidsgiver-frontend-workflows/.github/workflows/playwright-reusable.yml@main
    with:
      playwright-version: v1.56.1-jammy
      node-version: lts/*
      matrix: '{"shardIndex":[1,2,3,4],"shardTotal":[4]}'
    secrets:
      npm_reader_token: ${{ secrets.READER_TOKEN }}
