name: Produksjon

on:
  release:
    types: [released]
  push:
    branches:
      - 'prod/**'

env:
  APP: fritak-agp-frontend
  IMAGE: ghcr.io/${{ github.repository }}/fritak-agp-frontend:${{ github.sha }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  Bygg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: fritak-frontend-artifact
          path: ${{ github.workspace }}/dist/**/*

  Docker:
    needs: [Bygg]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v3
        with:
          name: fritak-frontend-artifact
          path: dist
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        run: |
          docker build --pull --tag ${{ env.IMAGE }}  .
          docker push ${{ env.IMAGE }}

  Deploy:
    needs: [Docker]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: helsearbeidsgiver
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: naiserator.yaml
          VARS: nais/prod-gcp.json
          REF: ${{ env.COMMIT }}
          IMAGE: ${{ env.IMAGE }}
