name: Bygg pull request

on:
  pull_request:
    branches:
      - main

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Bygg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm run-script build
      - uses: actions/upload-artifact@v2
        with:
          name: fritak-frontend-artifact
          path: ${{ github.workspace }}/build/**/*

  Kodekvalitet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci --no-build
      - run: npm test
      - run: node run-sonar.js

  Eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run-script lint

  Snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

