name: Bygg pull request

on:
  pull_request:
    branches:
      - main

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  Bygg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: "https://npm.pkg.github.com"
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: fritak-frontend-artifact
          path: ${{ github.workspace }}/build/**/*

  Kodekvalitet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: "https://npm.pkg.github.com"
      - run: yarn install --frozen-lockfile
      - run: yarn test

  Eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: "https://npm.pkg.github.com"
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  # TestCafe:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - run: yarn install --frozen-lockfile
  #     - name: Run tests
  #       uses: DevExpress/testcafe-action@latest
  #       with:
  #         skip-install: true
  #         args: chrome:headless tests/ --app-init-delay 60000 --app "yarn serve" --cache
